### ISSUE TITLE
When will the pertained models be released?

### ISSUE THREAD

**Issue by yypurpose** [frank-xwang/RIDE-LongTailRecognition#10]
Hi! You have provided the MODEL_ZOO.md. However, I found the Links in the page can not be clicked. I'm waiting for the release of the pertained models.

Thanks in advance.

**Comment by TonyLianLong** [comment]
Thanks for your interest in our work, and we'll release the final camera-ready paper and pretrained models in a one or two weeks, in accord to the formal deadline.

**Comment by frank-xwang** [comment]
The pretrained models are available now.
