### ISSUE TITLE
[Conceptual question] Are RIDE and EA used at the same time?

### ISSUE THREAD

**Issue by Kouuh** [frank-xwang/RIDE-LongTailRecognition#12]
**Describe the error** A clear and concise description of what your question is.
I check that the loss used in the ride_ea.json configuration file is -CrossEntropyLoss. The loss used in the ride.json configuration file is RIDELoss. Therefore, the paper proposes that RIDELoss and EA Module can improve performance respectively. Rather than combining the two.

**Comment by frank-xwang** [comment]
Hi! Yes, the EA module is only applied in the second stage for reducing the overall computational cost.
