### ISSUE TITLE
[Error] An python exception is encountered at stage 2

### ISSUE THREAD

**Issue by YifanZhang07** [frank-xwang/RIDE-LongTailRecognition#13]
**Describe the error** A clear and concise description of what the problem is.
Hi, thanks for your great work. 

After training Stage 1 and obtain the checkpoint, I start running the code for stage 2. However, there is an error "RuntimeError: grad can be implicitly created only for scalar outputs" in self._train_epoch(epoch). Google said this is because the loss is not scalar. I have no idea what is wrong with this code since it is packaged very well. Expect your reply.

**Comment by TonyLianLong** [comment]
Hi Vanint,

If possible, could you print out the loss so that it is possible to see whether it's a scalar or not? Thanks.

Tony

**Comment by YifanZhang07** [comment]
Hi Tony, when I print out the loss in trainer/trainer.py and find loss=tensor([0.8319, 0.3289]). It is strange.

**Comment by YifanZhang07** [comment]
I find the mistake is due to two GPUs during stage 2. If I change to 1 GPU for stage 2, the issue does not appear. Do you know any reason for this？ Thanks.

**Comment by TonyLianLong** [comment]
Hi, we don't currently support multi-GPU training for stage 2. Stage 2 usually involves only a few epochs, which should be fast. However, if you would like to use more GPUs in training, taking mean of the losses from multiple GPUs may be a potential choice.

**Comment by frank-xwang** [comment]
Closing it. Feel free to reopen it if you have more questions.
