### ISSUE TITLE
 Could you release the code that measure the bias and variance?

### ISSUE THREAD

**Issue by YananGu** [frank-xwang/RIDE-LongTailRecognition#14]
Thanks!

**Comment by frank-xwang** [comment]
Hi, currently, we may don't have the plan to support bias-variance calculation. But we will add it to TODO list. You should be able to get the value easily by following the descriptions in our paper. We have updated the bias-variance part of the [paper](http://people.eecs.berkeley.edu/~xdwang/papers/ICLR2021_RIDE.pdf) to make it easier to understand. Feel free to re-open the issue if you have more questions!
