### ISSUE TITLE
CIFAR 10 support?

### ISSUE THREAD

**Issue by liming-ai** [frank-xwang/RIDE-LongTailRecognition#15]
thanks for your contribution, do you have any plans to support cifar10 dataset?

**Comment by frank-xwang** [comment]
Hello, this repo is to reproduce the results reported in the paper, so, unfortunately, we will only provide support for datasets which are experimented in the paper. The CIFAR-10 and CIFAR-100 dataloader should be quite similar, you may only need to change a few line of codes to make CIFAR-100 dataloader workable for CIFAR-10. We will be happy to provide necessary help if you encounter any problems when you are implementing it.
