### ISSUE TITLE
Can you release the resulting model from the first phase of training?

### ISSUE THREAD

**Issue by abababa-ai** [frank-xwang/RIDE-LongTailRecognition#16]
This is excellent work in the direction of long tail recognition. I've been following your work and codes recently, also attempting to reproduce the results in the paper using your code. But I don't have enough computational resources to conduct the experiment. Can you release the resulting models from the first stage of training.

**Comment by TonyLianLong** [comment]
Hi @abababa-ai ,

If you remove the expert selection parameters from the model state_dict, you can load the model without using the expert assignment. In this way, you get the same parameters as in the first part. We freeze the network except the expert assignment in the second stage training, and the parameters of the network is the same in the stage 2 and is released in checkpoint.

**Comment by abababa-ai** [comment]
ok, get it, thanks
