### ISSUE TITLE
[Error] An error that may cause the "reweight" flag to fail

### ISSUE THREAD

**Issue by Chen-Wendi** [frank-xwang/RIDE-LongTailRecognition#23]
Hi, I got some errors in the class `RIDELoss()` in `loss.py`. 
It seems that if I set the "reweight" flag of loss to be false in the configuration file, there would be an **AttributeError** which says *'RIDELoss' object has no attribute 'per_cls_weights_base'*. I think you may set `self.per_cls_weights_base` to be `None` when `self.reweight_epoch == -1` in the function `_hook_before_epoch()` to solve this problem.

**Comment by frank-xwang** [comment]
Thanks for your suggestions, we will look into it.
