### ISSUE TITLE
Request for more results

### ISSUE THREAD

**Issue by Harry-hash** [frank-xwang/RIDE-LongTailRecognition#25]
It seems that currently only top-1 accuracy is reported after training on imagenet-LT, and I also see the script to compute top-k accuracy. I am wondering how can I get the performance on many-shot, medium-shot and few-shot?

**Comment by frank-xwang** [comment]
Hi, we have provided the script for testing the pre-trained checkpoints, please follow "Test" section of the instruction in README. The results reported during the training process is only for the sake of debugging. You can also modify it to report top-5 by calling top_k_acc function in RIDE-LongTailRecognition/model/metric.py and set k as 5. Feel free to re-oepn this issue and let us know if you have more problems.
