### ISSUE TITLE
the imagenet-lt dataset is note available

### ISSUE THREAD

**Issue by ToscanaGoGithub** [frank-xwang/RIDE-LongTailRecognition#27]
**Describe the error** A clear and concise description of what your question is.
we download the ImageNet-lt form google drive，but when we execute the ‘configs/config_imagenet_lt_resnet10_ride.json’，we find that should be 'train test val' folder in imagenet-lt dataset,but actually there not

**Comment by frank-xwang** [comment]
The ImageNet-LT train/val/test are based on the original ImageNet-1k dataset, since we don't have the permission to distribute it, you may need to download ImageNet-1k images from [the official website](https://image-net.org/download.php).
