### ISSUE TITLE
How to understand Formula 13 and 14 in your paper?

### ISSUE THREAD

**Issue by MRZHANG-1997** [frank-xwang/RIDE-LongTailRecognition#32]
**Describe the error** A clear and concise description of what your question is.
Thank you for your work in long-tailed recognition problem. Your work is excellent, and i want to use RIDE in my research file. However, i was confusion  in understanding formula 13 and 14. For example, what do γ means? and How to compute it? as well as what do α means? and How to compute it?

**Comment by TonyLianLong** [comment]
Please have a look at our loss function implementation. You don't need to re-implement it yourself if you just want to use it: https://github.com/frank-xwang/RIDE-LongTailRecognition/blob/main/model/loss.py#L124

**Comment by MRZHANG-1997** [comment]
Dear Tony,

Thank you very much for your help!



Sincerely your,

Sun










At 2022-06-18 12:21:03, "Long(Tony) Lian" ***@***.***> wrote:

Please have a look at our loss function implementation. You don't need to re-implement it yourself if you just want to use it: https://github.com/frank-xwang/RIDE-LongTailRecognition/blob/main/model/loss.py#L124
