### ISSUE TITLE
where is the routing module in the code?

### ISSUE THREAD

**Issue by cl475143764** [frank-xwang/RIDE-LongTailRecognition#8]
thanks for your excellent work,but i viewed the code and not found the routing module, could you give me a induce?

**Comment by frank-xwang** [comment]
Hi, you can find the expert assignment module in: https://github.com/frank-xwang/RIDE-LongTailRecognition/blob/main/model/fb_resnets/EAResNet.py. For more details about the ground truth of the routing expert module (aka expert assignment module), please check our paper. Please let us know if you have any other questions.

**Comment by cl475143764** [comment]
Thanks for your kind reply, goodluck



---Original---
